# Generated by Django 5.1.7 on 2025-03-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.JSONField(help_text='Current location coordinates {lat: float, lng: float}')),
                ('pickup_location', models.JSONField(help_text='Pickup location coordinates {lat: float, lng: float}')),
                ('dropoff_location', models.JSONField(help_text='Dropoff location coordinates {lat: float, lng: float}')),
                ('current_cycle_hours', models.FloatField(help_text='Current cycle hours used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(help_text='Stop location coordinates {lat: float, lng: float}')),
                ('stop_type', models.CharField(choices=[('REST', 'Required Rest Stop'), ('FUEL', 'Fuel Stop'), ('PICKUP', 'Pickup Location'), ('DROPOFF', 'Dropoff Location')], max_length=20)),
                ('planned_arrival', models.DateTimeField()),
                ('planned_departure', models.DateTimeField()),
                ('sequence', models.IntegerField(help_text='Stop sequence in the route')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routing.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ELDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duty_status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty Not Driving')], max_length=3)),
                ('location', models.JSONField(help_text='Location coordinates {lat: float, lng: float}')),
                ('remarks', models.TextField(blank=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='routing.trip')),
            ],
        ),
    ]
