# Generated by Django 5.1.7 on 2025-03-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_remove_trip_status_eldlog_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eldlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eldlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='updated_at',
        ),
    ]
